### ISSUE TITLE
Latest Codex version fails to convert Kindle books downloaded from Kindle version 1.24

### ISSUE THREAD

**Issue by Cambridgeport90** [jscholes/codex#11]
I am running both the latest Windows 10, the latest Codex, and the 1.24 iteration of the Kindle software (removed 1.25 and re-installed 1.24). I got errors when trying to convert files on 56 of 57 files (only the singular .mobi file I have actually converted properly. From the logs, it appears that there are errors in Python code,though they look more like programmatic errors rather than something that's user generated. I'll attach the log here as well so that you can see it. Advice would be appreciated. Thanks.
[codex2.log](https://github.com/jscholes/codex/files/4985574/codex2.log)

**Comment by jscholes** [comment]
The default filetype downloaded by Kindle versions higher than 1.17 is currently not supported.  I'll leave this issue open, because it is my plan to eventually have the new Amazon format be supported by Codex.  In the meantime, the options are:

1. Download Kindle for PC version 1.17.  I don't want to link to it directly here, but the filename is "KindleForPC-installer-1.17.44183.exe" and the file is available on the Internet.  Be sure to turn off automatic updates in version 1.24 first.
2. Disable the new file format in your current Kindle version by removing the `renderer-test` program and related files.  There are instructions available at: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md (search for the word "render" on that page or start reading from the heading: "A Recent Change to Kindle for PC/Kindle for Mac").

**Comment by Cambridgeport90** [comment]
Thanks!I had forgotten which version it is. I will tell you, though, you might have an interesting time getting the newest format to be supported. I have read that others were not able to break through it.

**Comment by toohoo** [comment]
Hello,
have Kindle 1.17. Codex does error on some files. Is there help for me? I had installed another way with Calibre before but this isn't working anymore. I see the book converting in the folder but it is removed after finish. Do you know anything about this issue?
Thanks in advance, best regards

**Comment by toohoo** [comment]
OK, seems it is no help here. What a pity! Wish the big Karma may be with you

**Comment by Cambridgeport90** [comment]
It's not that... it's because whatever Amazon uses in order to encrypt their books is very difficult to break through, and until a countermeasure is found, it will be impossible to convert their newest stuff using their latest update.

**Comment by jscholes** [comment]
The application is not actively maintained or supported.  Pre-built versions, and the corresponding project page, are no longer available.  As such, this will not likely be worked on.
