### ISSUE TITLE
cannot convert epub and chm files

### ISSUE THREAD

**Issue by gregjozk** [jscholes/codex#4]
Hi,

recently I instaled a codex to 64-bit w10 machine. when I tried to convert some files, a codex has shown an error. a log and source file is attached. as I understand, there can be unicode error?

thx.

regards, Jožef
[codex error.zip](https://github.com/jscholes/codex/files/836004/codex.error.zip)

**Comment by gregjozk** [comment]
here is another zip and log with debug logging enabled.
[codex error.zip](https://github.com/jscholes/codex/files/836013/codex.error.zip)

**Comment by jscholes** [comment]
Thanks for submitting the issue with logs.  Unfortunately this is a calibre limitation, caused by there being an accented character in your Windows username.  If you change your username and/or run Codex as another user, you'll probably find that the issue goes away.

As such, there's nothing I can really do about it at the moment, but other people have experienced this problem also so a work-around is on my to-do list.

**Comment by jscholes** [comment]
The application is not actively maintained or supported.  Pre-built versions, and the corresponding project page, are no longer available.  As such, this will not likely be worked on.
